In [8]:
import pandas as pd
import numpy as np
import scipy as sp
import chart_studio.plotly as py
import plotly.figure_factory as ff
chart_studio.tools.set_credentials_file(username='Gfinin3', )

In [25]:
import chart_studio

In [5]:
df = pd.read_csv('/Users/gregfinin/Downloads/comments_df_agg_plotly.csv')

In [6]:
df

      gme    amc     bb    date
0    2924     22    424  14-Dec
1    2682     12    913  15-Dec
2     946     34    997  16-Dec
3     599     38    733  17-Dec
4     348     46    677  18-Dec
5     470     20    413  19-Dec
6    1025     79    539  20-Dec
7    1123    109    536  21-Dec
8     587    110    495  22-Dec
9     763    107    960  23-Dec
10   1165     37    955  24-Dec
11    365     17    452  25-Dec
12    369     12    379  26-Dec
13   1071    108    588  27-Dec
14   3690     57    729  28-Dec
15   4494     41    733  29-Dec
16   2040     10    454  30-Dec
17    966     25    331  31-Dec
18   1050     29    312   1-Jan
19   1317     32    428   2-Jan
20   2935     73    549   3-Jan
21   2551     54    664   4-Jan
22   2056     56    537   5-Jan
23   3097     52    566   6-Jan
24   1012     21    337   7-Jan
25   1098      8    404   8-Jan
26    719      3    341   9-Jan
27   1782     10    537  10-Jan
28   1445     22    641  11-Jan
29   1220     10    923  12-Jan
30   1122     16   1041  13-Jan
31   1134      5   1358  14-Jan
32    464      4    886  15-Jan
33    742      6    672  16-Jan
34   2513     11    844  17-Jan
35   1273     18    799  18-Jan
36  11797     16    738  19-Jan
37  16050     23   4193  20-Jan
38  16038    157   9408  21-Jan
39   4730      9   2109  22-Jan
40   3832      9   1614  23-Jan
41   5860    112   2637  24-Jan
42   9986    253   5700  25-Jan
43   7716    179   6173  26-Jan
44   8988     87   5543  27-Jan
45  17342   1120  10039  28-Jan
46  10800    151   5972  29-Jan
47   3245     29   1383  30-Jan
48  41289  28415  18774  31-Jan
49  75240  32701  22594   1-Feb
50  59986  29956  17943   2-Feb
51  42644  24029  10989   3-Feb
52  42689  18493   8405   4-Feb
53  49206  31592   9870   5-Feb
54  44371  21521   6130   6-Feb
55   3334   1483    616   7-Feb

In [22]:
import plotly.graph_objects as go
from plotly.offline import plot

In [26]:
chart_studio.tools.set_credentials_file(username='Gfinin3', api_key='bKGMtXssJ8qljnjy6Ao5')

In [27]:
data = [go.Bar(x=df.date,
            y=df.gme)]

py.iplot(data, filename='jupyter-basic_bar')